## Training time: ~2.5h
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export NPROC_PER_NODE=8
# export MAX_PIXELS=1003520 
# export WANDB_BASE_URL=https://api.wandb.ai 
export USE_HF=1 
# DISABLE_VERSION_CHECK=1 FORCE_TORCHRUN=1 NNODES=4 NODE_RANK=$RANK MASTER_ADDR=$MASTER_ADDR MASTER_PORT=29500 \
# FORCE_TORCHRUN=1 \
DISABLE_VERSION_CHECK=1 FORCE_TORCHRUN=1 NNODES=1 NODE_RANK=$RANK MASTER_ADDR=$MASTER_ADDR MASTER_PORT=29500 \
    llamafactory-cli train examples/train_full/avar_sft.yaml